name: Secure File Uploader

on:
  repository_dispatch:
    types: [upload-file]

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check if file exists
        id: check
        run: |
          if [ -f "${{ github.event.client_payload.file_name }}" ]; then
            echo "exists=true" >> $GITHUB_ENV
          else
            echo "exists=false" >> $GITHUB_ENV
          fi

      - name: Upload File (if not exists)
        if: env.exists == 'false'
        run: |
          echo "${{ github.event.client_payload.file_content }}" | base64 --decode > ${{ github.event.client_payload.file_name }}
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add ${{ github.event.client_payload.file_name }}
          git commit -m "Uploaded ${{ github.event.client_payload.file_name }}"
          git push

      - name: Return File Link
        run: |
          echo "file_url=https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ github.event.client_payload.file_name }}" >> $GITHUB_ENV
